name: hw5

services:
  questdb:
    image: questdb/questdb:8.1.4
    ports:
      - 9000:9000 # REST API and Web Console
      - 9009:9009 # InfluxDB Line Protocol
      - 8812:8812 # Postgres Wire Protocol
      - 9003:9003 # Healthcheck
    volumes:
      - hw5_data:/var/lib
    networks:
      - app_network

  # Define any additional services here
  # ---
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=host=questdb port=8812 dbname=qdb user=admin password=quest
      - API_URL=http://api:8000
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET}
    depends_on:
      - questdb
    networks:
      - app_network

  main:
    build:
      context: .
      dockerfile: Dockerfile.main
    command: ["python", "main.py"]
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET}
      - TRADE_DAYS=5
      - CAPITAL_ALLOCATION_BUY_CLOSE_SELL_OPEN=5000
      - CAPITAL_ALLOCATION_SHORT_TERM_MOMENTUM=5000
      - CAPITAL_ALLOCATION_CUSTOM_STRATEGY=5000
      - SYMBOL_BUY_CLOSE_SELL_OPEN=AAPL
      - SYMBOL_SHORT_TERM_MOMENTUM=ALBT
      - SYMBOL_CUSTOM_STRATEGY=MSFT
    depends_on:
      - questdb
    networks:
      - app_network

  streaming:
    build:
      context: .
      dockerfile: Dockerfile.streaming
    command: ["python", "streaming.py"]
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

  # ---
volumes:
  hw5_data:
    external: true
  