name: lab5

services:
  questdb:
    image: questdb/questdb:8.1.4
    ports:
      - 9000:9000 # REST API and Web Console
      - 9009:9009 # InfluxDB Line Protocol
      - 8812:8812 # Postgres Wire Protocol
      - 9003:9003 # Healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/ping"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET}
      - QUESTDB_HOST=questdb
      - HISTORICAL_DAYS=${HISTORICAL_DAYS}
    depends_on:
      - questdb

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - QUESTDB_HOST=questdb
    ports:
      - 8000:8000

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - 8501:8501
    depends_on:
      - api

  trading-engine:
    build:
      context: .
      dockerfile: Dockerfile.engine
    volumes:
      - ./logs:/app/logs
    environment:
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET}
      - SHARES_BUY_CLOSE_SELL_OPEN=${SHARES_BUY_CLOSE_SELL_OPEN}
      - SHARES_SHORT_TERM_MOMENTUM=${SHARES_SHORT_TERM_MOMENTUM}
      - SHARES_ORB_STRATEGY=${SHARES_ORB_STRATEGY}
      - SYMBOL_BUY_CLOSE_SELL_OPEN=${SYMBOL_BUY_CLOSE_SELL_OPEN}
      - SYMBOL_SHORT_TERM_MOMENTUM=${SYMBOL_SHORT_TERM_MOMENTUM}
      - SYMBOL_ORB_STRATEGY=${SYMBOL_ORB_STRATEGY}
      - MOMENTUM_WINDOW=${MOMENTUM_WINDOW}
      - MOMENTUM_THRESHOLD=${MOMENTUM_THRESHOLD}
      - STOP_LOSS_PCT=${STOP_LOSS_PCT}
      - ORB_WINDOW=${ORB_WINDOW}
      - ORB_BREAKOUT_PCT=${ORB_BREAKOUT_PCT}
      - ORB_STOP_LOSS_PCT=${ORB_STOP_LOSS_PCT}
      - ORB_TARGET_PCT=${ORB_TARGET_PCT}
    depends_on:
      - api
      - questdb

  trade_data:
    build:
      context: .
      dockerfile: Dockerfile.trade_data
    depends_on:
      - questdb
    environment:
      - QUESTDB_HOST=questdb
      - ALPACA_API_KEY=${ALPACA_API_KEY}
      - ALPACA_API_SECRET=${ALPACA_API_SECRET}