[build-system]
requires = ["setuptools>=70.0"]
build-backend = "setuptools.build_meta"

[project]
name = "backtestlib"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.1,<2.2",
    "pandas~=2.2,<2.3"
]

[tool.setuptools.packages.find]
where = ["src"]
